apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress
resources:
  - ../../base/ingress-nginx
patchesStrategicMerge:
  - release-patch.yaml
configMapGenerator:
  - name: ingress-nginx-values
    behavior: merge
    files:
      - dev-values.yaml
