apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: ingress
spec:
  releaseName: ingress-nginx-controller
  chart:
    spec:
      version: 4.1.3
  valuesFrom:
    - kind: ConfigMap
      name: ingress-nginx-values
      valuesKey: values.yaml
    - kind: ConfigMap
      name: ingress-nginx-values
      valuesKey: dev-values.yaml
