apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - namespace.yaml
  - release.yaml
configMapGenerator:
  - name: kube-prometheus-values
    files:
      - values.yaml
      - additional-scrape-config.yaml
  - name: grafana-dashboards
    files:
      - dashboards/cluster.json
      - dashboards/control-plane.json
      - dashboards/ingress-nginx-controller.json
    options:
      labels:
        grafana_dashboard: "1"
configurations:
  - kustomizeconfig.yaml
