# Default values
# https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml

## Prometheus
prometheus:
  service:
    sessionAffinity: ClientIP
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - prometheus.k8s.local

## Alert Manager
alertmanager: 
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - alert-manager.k8s.local
    path: /

## Grafana
grafana:
  ingress:
    enabled: true
    hosts:
      - grafana.k8s.local
    path: /
