apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - ../../base/prometheus
patchesStrategicMerge:
  - release-patch.yaml
configMapGenerator:
  - name: kube-prometheus-values
    behavior: merge
    files:
      - dev-values.yaml
