apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus
  namespace: monitoring
spec:
  chart:
    spec:
      version: 35.5.1
  valuesFrom:
    - kind: ConfigMap
      name: kube-prometheus-values
      valuesKey: values.yaml
    - kind: ConfigMap
      name: kube-prometheus-values
      valuesKey: additional-scrape-config.yaml
    - kind: ConfigMap
      name: kube-prometheus-values
      valuesKey: dev-values.yaml